### ISSUE TITLE
slnStartupProject clobbers Project Dependencies in MSVC 2008

### ISSUE THREAD

**Issue by ddurham2** [michaKFromParis/slnStartupProject#3]
So, just running it on a 2008 sln just causes all checkboxes to be unchecked seen under the startup project's dependencies (and probably all other projects')

Need more info?

**Comment by michakfromparis** [comment]
Hi,

Yes. Thanks for the feedback. Could you send me your sln file and I'll be
happy to fix the issue.

M

Thanks for the feedback. Could you

On Wednesday, May 20, 2015, ddurham2 notifications@github.com wrote:

> So, just running it on a 2008 sln just causes all checkboxes to be
> unchecked when going under the startup project's dependencies (and probably
> all other projects')
> 
> Need more info?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/michaKFromParis/slnStartupProject/issues/3.

## 

Michel Courtine | CEO | iVoltage
+33 6 189 354 89 | michaK@ivoltage.me
http://ivoltage.me

**Comment by ddurham2** [comment]
Hopefully the foo.zip attachment will make it through email... Let me 
know if not.

If you extract the zip, you'll find foo\foo-app.sln which references 3 
projects: foo-app, baz-app and bar-lib  where foo-app and baz-app both 
depend on the bar-lib

foo-app is already the startup project.

If you run "slnStartupProject foo-app.sln foo-app", then open the sln 
back in MSVC 2008, you'll find that it clobbers the dependency of 
foo-app on bar-lib.   I diffed the sln file from before and after the 
run, and it looks like it's messing up one of the the XML tag names a 
bit.  So I wouldn't think the fix should be too hard.

Thanks!

**Comment by michakfromparis** [comment]
Unfortunately, the attachment didn't make it through. Could you please send it to github ---at--- michak.net ?
