### ISSUE TITLE
What about multiple startup projects support?

### ISSUE THREAD

**Issue by mayerwin** [michaKFromParis/slnStartupProject#4]

**Comment by michakfromparis** [comment]
Hi,

Could you elaborate? Afaik, there can only be one startup project per
solution file

On Tuesday, August 25, 2015, mayerwin notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/michaKFromParis/slnStartupProject/issues/4.

## 

Michel Courtine | CEO | iVoltage
+33 6 189 354 89 | michaK@ivoltage.me
http://ivoltage.me

**Comment by mayerwin** [comment]
Actually, if you right click on the solution name, then Properties, you can choose "Multiple startup projects" and there select which projects you want started at the same time (useful for debugging a client/server application for example).

**Comment by michakfromparis** [comment]
Indeed. I just checked the option in Visual Studio, it's there. Unfortunately, I just diff'ed the .sln file and there is absolutely no modification to it when you set multiple startup projects. This means that Visual Studio stores these settings in the .suo file.
The .suo file format is closed and binary. It also changes with every new version of Visual Studio. This means I can't write a generic approach. On top of that, the .suo file is a user space setting and should not checked into source control. Bummer.
If you have time for it, you could try to reverse engineer it and submit a PR.

**Comment by michakfromparis** [comment]
Haven't heard back from you. Should I close the issue?

**Comment by mayerwin** [comment]
Yes you can, I have no immediate use for the tool so I don't expect to dig further into the topic myself (if I ever do, I will submit a PR).
